config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'full_texts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :full_texts do
    resources :text_paragraphs, only: [:index]
  end
  resources :text_paragraphs, only: [:show]
  patch 'text_paragraphs/:id/mark_as_done', to: 'text_paragraphs#mark_as_done', as: :mark_as_done

  resources :game_sessions, only: [:show]

  post 'text_paragraphs/:text_paragraph_id/game_sessions', to: 'game_sessions#create', as: :create_game_session
  post 'game_sessions/:id/update', to: 'game_sessions#update', as: :update_game_session
  post 'game_sessions/:id/guess_word', to: 'game_sessions#guess_word', as: :guess_word
  get 'game_sessions/:id/final_score', to: 'game_sessions#final_score', as: :final_score


  resources :game_two_sessions, only: [:show]

  post 'text_paragraphs/:text_paragraph_id/game_two_sessions', to: 'game_two_sessions#create', as: :create_game_two_session
  post 'game_two_sessions/:id/update', to: 'game_two_sessions#update', as: :update_game_two_session
  post 'game_two_sessions/:id/guess_word', to: 'game_two_sessions#guess_word', as: :guess_word_two
  get 'game_two_sessions/:id/final_score', to: 'game_two_sessions#final_score', as: :final_score_two
  
  get 'dashboard', to: "pages#dashboard"

end

app/models/game_session.rb
class GameSession < ApplicationRecord
  belongs_to :text_paragraph
  belongs_to :game

  def chop_paragraph
    text = text_paragraph.content.split(/\b/)
    count = 1
    magic_count = rand(3..8)
    text.map do |word|
      if count % magic_count == 0 && word.match(/\w+/)
        count = 1
        magic_count = rand(3..8)
        { secret_word: word }
      elsif word.match(/\w+/)
        count += 1
        word
      else
        word
      end
    end
  end
end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:guess_word]

  def show
    @game_session = GameSession.find(params[:id])
    @chopped_paragraph = @game_session.chop_paragraph
    input_count = @chopped_paragraph.count { |element| element.is_a? Hash }
    @game_session.number_of_inputs = input_count
    @game_session.number_of_right_inputs = 0
    @game_session.save
  end

  def new
    @game_session = GameSession.new
  end

  def create
    @game_session = GameSession.new
    @text_paragraph = TextParagraph.find(params[:text_paragraph_id])
    @game_session.text_paragraph = @text_paragraph
    @game_session.game = Game.first
    if @game_session.save
      redirect_to game_session_path(@game_session)
    else
      render :new
    end
  end

  def guess_word
    @game_session = GameSession.find(params[:id])
    if params[:guess].downcase == params[:answer].downcase
      @game_session.number_of_right_inputs += 1
      @game_session.save!
      render json: {success: true}
    else
      render json: {success: false}
    end
  end

  def final_score
    @game_session = GameSession.find(params[:id])
    render json: { finalScore: @game_session.number_of_right_inputs, inputs: @game_session.number_of_inputs}
  end

  def input_count
    @game_session = GameSession.find(params[:id])
    render json: {inputCount: @game_session.number_of_inputs}
  end

  # def insert_word_game(words)
  #   text = words.split
  #   text.map.with_index do |word, idx|
  #     idx % 6 == 0 ? "_" * text.length : text
  #   end.join
  # end
end

app/views/game_sessions/show.html.erb
<div class="game_session_background_container">
  <div class="game_session_main_container">
    <div class="game_session_game_container">
      <div class="game_session_header_container">
        <h1>Fill in the gaps</h1>
        <h3><%= @game_session.text_paragraph.full_text.title %></h3>
      </div>
      <%= form_tag(update_game_session_path, method: :post, id: "insert_word_game_form", data: { game_session_id: @game_session.id }) do %>
        <p>
          <% count = 1 %>
          <% @chopped_paragraph.each do |section| %>
            <% if section.is_a? Hash %>
                <%= text_field_tag "word#{count}", nil, class: "insert_word_input text-center", placeholder: "______", style: "width: #{section[:secret_word].length * 30}px",data: { answer: section[:secret_word] } %>
              <% count += 1 %>
            <% else %>
              <%= section %>
            <% end %>
          <% end %>
        </p>
      <% end %>
      <div class="game1_popup_window_background">
        <div id="game1_popup_window">
          <h1>Great try!</h1>
          <h3></h3>
          <div class="btn_retry_game_popup" id="game_one_retry_button_popup"><i class="fas fa-times"></i></div>
        </div>
      </div>
    </div>
    <%= link_to create_game_session_path(@game_session.text_paragraph), method: :post, class:"btn_retry_game_one" do %>
      <i class="fas fa-undo-alt"></i>
    <% end %>

     <%= link_to "Word Guess", create_game_two_session_path(@game_session.text_paragraph), method: :post, class:"blue-btn-on-game1-page" %>


  </div>
</div>

      <%= javascript_pack_tag 'insert_word_game' %>
      <%= javascript_pack_tag 'finished_game_popup' %>