config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'full_texts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :full_texts do
    resources :text_paragraphs, only: [:index]
  end
  resources :text_paragraphs, only: [:show]
  patch 'text_paragraphs/:id/mark_as_done', to: 'text_paragraphs#mark_as_done', as: :mark_as_done

  resources :game_sessions, only: [:show]

  post 'text_paragraphs/:text_paragraph_id/game_sessions', to: 'game_sessions#create', as: :create_game_session
  post 'game_sessions/:id/update', to: 'game_sessions#update', as: :update_game_session
  post 'game_sessions/:id/guess_word', to: 'game_sessions#guess_word', as: :guess_word
  get 'game_sessions/:id/final_score', to: 'game_sessions#final_score', as: :final_score


  resources :game_two_sessions, only: [:show]

  post 'text_paragraphs/:text_paragraph_id/game_two_sessions', to: 'game_two_sessions#create', as: :create_game_two_session
  post 'game_two_sessions/:id/update', to: 'game_two_sessions#update', as: :update_game_two_session
  post 'game_two_sessions/:id/guess_word', to: 'game_two_sessions#guess_word', as: :guess_word_two
  get 'game_two_sessions/:id/final_score', to: 'game_two_sessions#final_score', as: :final_score_two
  
  get 'dashboard', to: "pages#dashboard"

end

app/models/game_two_session.rb
class GameTwoSession < ApplicationRecord
  belongs_to :text_paragraph
  belongs_to :game

  def chop_paragraph
    text = text_paragraph.content.split(/\b/)
    count = 0
    text.map! do |word|
      if count == 0 && word.match(/\w+/)
        { secret_word: word }
      else
        word
      end
    end
  end
end

app/controllers/game_two_sessions_controller.rb
class GameTwoSessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:guess_word]
  def show
    @game_two_session = GameTwoSession.find(params[:id])
    @chopped_paragraph = @game_two_session.chop_paragraph
    @chopped_only_text = []
    @chopped_paragraph.each{|text| @chopped_only_text << text[:secret_word] if text.class == Hash }
    input_count = @chopped_paragraph.count { |element| element.is_a? Hash }
    @game_two_session.number_of_inputs = input_count
    @game_two_session.number_of_right_inputs = 0
    @game_two_session.save
  end

  def new
    @game_two_session = GameTwoSession.new
  end

  def create
    @game_two_session = GameTwoSession.new
    @text_paragraph = TextParagraph.find(params[:text_paragraph_id])
    @game_two_session.text_paragraph = @text_paragraph
    @game_two_session.game = Game.last
    if @game_two_session.save
      redirect_to game_two_session_path(@game_two_session)
    else
      render :new
    end
  end

  def guess_word
    @game_two_session = GameTwoSession.find(params[:id])
    if params[:guess].downcase == params[:answer].downcase
      @game_two_session.number_of_right_inputs += 1
      @game_two_session.save!
      render json: {success: true}
    else
      render json: {success: false}
    end
  end

  def final_score
    @game_two_session = GameTwoSession.find(params[:id])
    render json: { finalScore: @game_two_session.number_of_right_inputs, inputs: @game_two_session.number_of_inputs}
  end
end

app/views/game_two_sessions/show.html.erb
<div class="game_two_session_background_container">
  <div class="game_session_main_container">
    <div class="game_session_game_container">
      <div class="game_two_session_header_container">
        <h1>Guess the next word</h1>
        <h3><%= @game_two_session.text_paragraph.full_text.title %></h3>
      </div>
      <% first_section = @chopped_paragraph.first %>
      <% first_options = @chopped_only_text.uniq.reject{ |k| k == first_section[:secret_word]}.sample(3) + [first_section[:secret_word]] %>
      <%= form_tag(update_game_two_session_path, method: :post, id: "insert_word_game_two_form", data: { game_two_session_id: @game_two_session.id }) do %>
        <p>
          <% @chopped_paragraph.each do |section| %>
            <% if section.is_a? Hash %>
              <% options = [] %>
              <% options << @chopped_only_text.uniq.reject{ |k| k == section[:secret_word]}.sample(3) %>
              <% options << section[:secret_word] %>
                <span id='word_options' class="insert_word_input text-center" data-options=<%= options.flatten.shuffle.join(";") %> data-answer=<%= section[:secret_word] %> >
                </span>
            <% else %>
              <span class="punctuation"><%= section %></span>
            <% end %>
          <% end %>
        </p>
      <% end %>

       <span class="user-options-container d-none" id="options-container">
          <% first_options.shuffle.each_with_index do |option, idx| %>
            <span class='user-options' id="option-<%= idx + 1 %>"><%= option %></span>
          <% end %>
        </span>

      <div class="game1_popup_window_background">
        <div id="game1_popup_window">
          <h1>Great try!</h1>
          <h3></h3>
          <%= link_to create_game_two_session_path(@game_two_session.text_paragraph), method: :post, class:"btn_retry_game_popup" do %>
              <i class="fas fa-undo-alt"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

      <%= javascript_pack_tag 'multiple_choice_game' %>
      <%= javascript_pack_tag 'finished_game_popup' %>