config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'full_texts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :full_texts do
    resources :text_paragraphs, only: [:index]
  end
  resources :text_paragraphs, only: [:show]
  patch 'text_paragraphs/:id/mark_as_done', to: 'text_paragraphs#mark_as_done', as: :mark_as_done

  resources :game_sessions, only: [:show]

  post 'text_paragraphs/:text_paragraph_id/game_sessions', to: 'game_sessions#create', as: :create_game_session
  post 'game_sessions/:id/update', to: 'game_sessions#update', as: :update_game_session
  post 'game_sessions/:id/guess_word', to: 'game_sessions#guess_word', as: :guess_word
  get 'game_sessions/:id/final_score', to: 'game_sessions#final_score', as: :final_score


  resources :game_two_sessions, only: [:show]

  post 'text_paragraphs/:text_paragraph_id/game_two_sessions', to: 'game_two_sessions#create', as: :create_game_two_session
  post 'game_two_sessions/:id/update', to: 'game_two_sessions#update', as: :update_game_two_session
  post 'game_two_sessions/:id/guess_word', to: 'game_two_sessions#guess_word', as: :guess_word_two
  get 'game_two_sessions/:id/final_score', to: 'game_two_sessions#final_score', as: :final_score_two
  
  get 'dashboard', to: "pages#dashboard"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <% if (action_name == "show" && controller_name == "text_paragraphs") %>
    <%= link_to full_text_text_paragraphs_path(@text_paragraph.full_text), class:"btn_navbar_back" do %>
    <%= image_tag "arrow-white.png" %>
    <% end  %>
  <% elsif (action_name == "show" && controller_name == "game_sessions") %>
    <%= link_to full_text_text_paragraphs_path(@game_session.text_paragraph.full_text), class:"btn_navbar_back" do %>
    <%= image_tag "arrow-white.png" %>
    <% end  %>
    <% else (action_name == "show" && controller_name == "game_two_sessions") %>
    <%= link_to text_paragraph_path(@game_two_session.text_paragraph), class:"btn_navbar_back" do %>
    <%= image_tag "arrow-white.png" %>
    <% end  %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, height: 120, width: 120, crop: :fill, gravity: :face %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>