config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'full_texts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :full_texts do
    resources :text_paragraphs, only: [:index]
  end
  resources :text_paragraphs, only: [:show]
  patch 'text_paragraphs/:id/mark_as_done', to: 'text_paragraphs#mark_as_done', as: :mark_as_done

  resources :game_sessions, only: [:show]

  post 'text_paragraphs/:text_paragraph_id/game_sessions', to: 'game_sessions#create', as: :create_game_session
  post 'game_sessions/:id/update', to: 'game_sessions#update', as: :update_game_session
  post 'game_sessions/:id/guess_word', to: 'game_sessions#guess_word', as: :guess_word
  get 'game_sessions/:id/final_score', to: 'game_sessions#final_score', as: :final_score


  resources :game_two_sessions, only: [:show]

  post 'text_paragraphs/:text_paragraph_id/game_two_sessions', to: 'game_two_sessions#create', as: :create_game_two_session
  post 'game_two_sessions/:id/update', to: 'game_two_sessions#update', as: :update_game_two_session
  post 'game_two_sessions/:id/guess_word', to: 'game_two_sessions#guess_word', as: :guess_word_two
  get 'game_two_sessions/:id/final_score', to: 'game_two_sessions#final_score', as: :final_score_two
  
  get 'dashboard', to: "pages#dashboard"

end

app/models/text_paragraph.rb
class TextParagraph < ApplicationRecord
  has_many :game_sessions, dependent: :destroy
  belongs_to :full_text
  validates :content, presence: true
  validates :order_number, presence: true
end

app/controllers/text_paragraphs_controller.rb
class TextParagraphsController < ApplicationController
  before_action :set_text_paragraph, only: :show

  skip_before_action :verify_authenticity_token, only: [:guess_word]

  def index
    @full_text = FullText.find(params[:full_text_id])
    @text_paragraphs = @full_text.text_paragraphs.order(order_number: :asc)
  end

  def show
  end

  def mark_as_done
    @text_paragraph = TextParagraph.find(params[:id])
    @text_paragraph.done = !@text_paragraph.done
    @text_paragraph.save
  end

  def set_text_paragraph
    @text_paragraph = TextParagraph.find(params[:id])
  end
end

app/views/text_paragraphs/_mark_as_done_button.html.erb
<% if paragraph.done %>
  <i class="fas fa-check-circle green-icon transform"></i>
<% else %>
  <i class="fas fa-times-circle red-icon"></i>
<% end %>

app/views/text_paragraphs/index.html.erb
<div class="text-paragraphs-index-background">
  <div class="section section-header-backgraound">
    <div class="first-row-content">
      <div class="first-row-content-top">
        <div class="first-row-content-back-button">
          <%= link_to full_texts_path, class:"btn_navbar_back" do %>
            <%= image_tag "arrow-purple.png" %>
          <% end  %>
        </div>
        <div class="header-text"><h1>Text paragraph list</h1>
        </div>
        <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, height: 120, width: 120, crop: :fill, gravity: :face %>
      </div>
      <p class="lead text-center mb-5" style="color: #5151CC; font-size: 28px;"><%= @full_text.title %></p>
    </div>
  </div>
    <div class="mb-3"></div>
  <div class="container pb-5">
    <div class="row">
      <div class="col-12">
        <% @text_paragraphs.each do |paragraph| %>
          <div class="text-card-solid-border">
            <p class="text-content"><%= paragraph.content %></p>
            <p class="card-number-integer"><%= paragraph.order_number %></p>
            <div class="done-or-not-icon">
              <%= link_to mark_as_done_path(paragraph), remote: true, method: :patch, class: "white-link", id: "mark-as-done-#{paragraph.id}" do %>
                <%= render 'mark_as_done_button', paragraph: paragraph %>
              <% end %>
              <div class="background-icon-wrapper">
                <div class="white-icon-bg"></div>
              </div>

            </div>

            <div class="div-wraper d-flex">
              <div class="d-flex align-items-center justify-content-center game-options">
                <div><strong>Play </strong></div>
                <div><%= link_to "Gap Game", create_game_session_path(paragraph), method: :post, class: "to-game-one-button" %>
                </div>
                <div><%= link_to "Word Guess", create_game_two_session_path(paragraph), method: :post, class: "to-game-two-button" %>
                </div>
              </div>
              <div class="d-flex align-items-center justify-content-center read-listen-options">
                <div><strong>Listen </strong></div>
                <div><%= link_to "Paragraph", text_paragraph_path(paragraph), class: "to-listen-to-button" %>
                </div>
              </div>
            </div>





          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>



<!-- <div class="not-done-icon"><i class="fas fa-times-circle"></i></div> -->

app/views/text_paragraphs/mark_as_done.js.erb
function changeIcon(innerHTML) {
  const markAsDoneIcon = document.getElementById('mark-as-done-<%= @text_paragraph.id %>');
  markAsDoneIcon.innerHTML = innerHTML;
  markAsDoneIcon.classList.add("move-me");
}

changeIcon('<%= j render "text_paragraphs/mark_as_done_button", paragraph: @text_paragraph %>')

app/views/text_paragraphs/show.html.erb
<!-- <div class="remembex_header">
</div> -->

<div class="text_paragraph_background_container">

  <div class="text_paragraph_show_main_container">
    <div class="text_paragraph_show_container">
      <div class="text_paragraph_header_container">
          <h1 class="text_paragraph_show_title"><%= @text_paragraph.full_text.title %></h1>
      </div>
          <p class="text_paragraph_show_text"><%= @text_paragraph.content %></p>

      <!--
      <button onclick="responsiveVoice.speak('<%= @text_paragraph.content %>');"
      type="button" value="Play">Play</button>

      <button onclick="responsiveVoice.pause('<%= @text_paragraph.content %>');"
      type="button" value="Play">Pause</button>

      <button onclick="responsiveVoice.resume('<%= @text_paragraph.content %>');"
      type="button" value="Play">Resume</button> -->

      <a href="#" id="voice-btn" data-content="<%= @text_paragraph.content %>" data-state="initial" class="btn_listen"><i class="fas fa-play"></i></a>
      <%= link_to "Gap Game", create_game_session_path(@text_paragraph), method: :post, class:"btn_play_game" %>
      <%= link_to "Word Guess", create_game_two_session_path(@text_paragraph), method: :post, class:"btn_play_game2" %>
    </div>
  </div>
</div>

  <!-- temporary spot for game button, unclickable in original spot -->
    <%# link_to "Go to games!", create_game_session_path(@text_paragraph), method: :post, class: "btn_play_game" %>

    <script src="https://code.responsivevoice.org/responsivevoice.js?key=JXrgWNPm"></script>

    <%= javascript_pack_tag "read_aloud" %>